
volumes:
  ca-certs:
    name: impersonate-proxy-ca-certs


services:

  impersonate-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: impersonate-proxy
    ports:
      - "8899:8899"
    environment:
      - IMPERSONATE_PROXY_HOST=0.0.0.0
      - IMPERSONATE_PROXY_PORT=8899
      - IMPERSONATE_PROXY_IMPERSONATE=chrome
      - IMPERSONATE_PROXY_DEBUG=false
      - IMPERSONATE_PROXY_CA_DIR=/certs
    volumes:
      - ca-certs:/certs
    restart: unless-stopped
